### ISSUE TITLE
Agha Pas Key Responsivesh Mikoni ?

### ISSUE THREAD

**Issue by Marcouzz** [AHSharifi/Admin-Page#1]
dadash be khoda man 5 mahe montazeram ino responsive kni copy konam befrusham pls responsive kon 😢

**Comment by AHSharifi** [comment]
ishala ta hafte bad

**Comment by Marcouzz** [comment]
Kiram to Dahanet  Ta 2 min Dige Bede Age Nadi Foshet Midam

**Comment by AHSharifi** [comment]
> Kiram to Dahanet Ta 2 min Dige Bede Age Nadi Foshet Midam

ok

**Comment by Marcouzz** [comment]
:(

**Comment by Marcouzz** [comment]
agha chi shod pas
